### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by zangmolk** [AzeezDa/eqsolver#12]
hi
I got errors for last line of code when I run this example. I run this example in RustRover IDE:

**example:**
use eqsolver::multivariable::MultiVarNewtonFD;
use nalgebra::{vector, Vector2};

let f = |v: Vector2<f64>| vector![v[0].powi(2) - v[1] - 1., v[0] * v[1] - 2.];
let solution = MultiVarNewtonFD::new(f).solve(vector![1., 1.]); // Starting guess is (1, 1)

**errors:**
error[E0631]: type mismatch in closure arguments
error[E0599]: the method `solve` exists for struct `MultiVarNewtonFD<_, _, {closure@src\main.rs:39:14: 39:31}>`, but its trait bounds were not satisfied

your sincerity
Behnam

**Comment by AzeezDa** [comment]
Hello @zangmolk 
Thank you for submitting the issue.

It seems that you missed adding a generic type for the `Vector2` type

```rust
use eqsolver::multivariable::MultiVarNewtonFD;
use nalgebra::{vector, Vector2};

fn main() {
    //                 vvvvv You should specify what the type of the Vector2 is
    let f = |v: Vector2<f64>| vector![v[0].powi(2) - v[1] - 1., v[0] * v[1] - 2.];
    let solution = MultiVarNewtonFD::new(f).solve(vector![1., 1.]); // Starting guess is (1, 1)
    println!("{:?}", solution);
}
```

Does this help with your problem?

Best regards

**Comment by zangmolk** [comment]
Hi. thank you for your answer. but I have that's error again.

<img width="1880" height="1127" alt="Image" src="https://github.com/user-attachments/assets/b88082dd-0fb0-4fdf-882e-6d6547b08203" />

**Comment by AzeezDa** [comment]
Hi,

What version of Rust are you using?

The snippet I sent works on the latest stable version 1.91.1
